### PR TITLE
Hello, I made some changes/improvements in the random number comparison.

### PR DESCRIPTION
**Pull request by huntercas315**
Hello, I changed the imports and replaced the responses with fstrings because I was bored. I have now cleaned up some of the music inputs, but I will go no further into the a, b, and c's of thou variables.

### CODE REVIEW

**Review by dejMatt — APPROVED** [review]

**Comment by dejMatt** [comment]
Thanks! it makes everything look cleaner

**Comment by huntercas315** [comment]
Anytime :)

**Review by huntercas315 — COMMENTED** [review]
reviewed?

**Comment by dejMatt** [comment]
Yep

**Pull request merged**
